export type TarotCard = {
  name_en: string;
  name_th: string;
  name: string; // This will be dynamically populated
  image: string;
  meaning_up_en: string;
  meaning_up_th: string;
  meaning_up: string; // This will be dynamically populated
  meaning_rev_en: string;
  meaning_rev_th: string;
  meaning_rev: string; // This will be dynamically populated
  keywords: string[];
};

export const tarotCards: TarotCard[] = [
  // MAJOR ARCANA (22 cards)
  {
    name_en: "The Fool",
    name_th: "เดอะฟูล",
    name: "The Fool",
    image: "/images/major_arcana_fool_result.webp",
    meaning_up_en: "New beginnings, freedom, adventure",
    meaning_up_th: "การเริ่มต้นใหม่, อิสระ, การผจญภัย",
    meaning_up: "New beginnings, freedom, adventure",
    meaning_rev_en: "Recklessness, lack of planning, hesitation",
    meaning_rev_th: "ความประมาท, ขาดการวางแผน, ความลังเล",
    meaning_rev: "Recklessness, lack of planning, hesitation",
    keywords: ["jester", "cliff"]
  },
  {
    name_en: "The Magician",
    name_th: "เดอะเมจิเชียน",
    name: "The Magician",
    image: "/images/major_arcana_magician_result.webp",
    meaning_up_en: "Power, action, control",
    meaning_up_th: "ความสามารถ, การลงมือทำ, การควบคุมสถานการณ์",
    meaning_up: "Power, action, control",
    meaning_rev_en: "Deception, lack of confidence, misuse of power",
    meaning_rev_th: "การหลอกลวง, ขาดความมั่นใจ, ใช้ความสามารถในทางที่ผิด",
    meaning_rev: "Deception, lack of confidence, misuse of power",
    keywords: ["magician", "alchemy"]
  },
  {
    name_en: "The High Priestess",
    name_th: "เดอะไฮพรีสเตส",
    name: "The High Priestess",
    image: "/images/major_arcana_priestess_result.webp",
    meaning_up_en: "Intuition, secrets, inner knowledge",
    meaning_up_th: "สัญชาตญาณ, ความลับ, ความรู้ภายใน",
    meaning_up: "Intuition, secrets, inner knowledge",
    meaning_rev_en: "Secrets revealed, lack of understanding, ignoring intuition",
    meaning_rev_th: "ความลับถูกเปิดเผย, ขาดความเข้าใจ, ไม่ฟังเสียงในใจ",
    meaning_rev: "Secrets revealed, lack of understanding, ignoring intuition",
    keywords: ["priestess", "moon"]
  },
  {
    name_en: "The Empress",
    name_th: "ดิเอ็มเพรส",
    name: "The Empress",
    image: "/images/major_arcana_empress_result.webp",
    meaning_up_en: "Abundance, love, care",
    meaning_up_th: "ความอุดมสมบูรณ์, ความรัก, การดูแล",
    meaning_up: "Abundance, love, care",
    meaning_rev_en: "Scarcity, over-controlling, family issues",
    meaning_rev_th: "ความขาดแคลน, การควบคุมมากเกินไป, ปัญหาครอบครัว",
    meaning_rev: "Scarcity, over-controlling, family issues",
    keywords: ["empress", "nature"]
  },
  {
    name_en: "The Emperor",
    name_th: "ดิเอ็มเพอเรอร์",
    name: "The Emperor",
    image: "/images/major_arcana_emperor_result.webp",
    meaning_up_en: "Authority, control, stability",
    meaning_up_th: "อำนาจ, การควบคุม, ความมั่นคง",
    meaning_up: "Authority, control, stability",
    meaning_rev_en: "Abuse of power, lack of stability, stubbornness",
    meaning_rev_th: "การใช้อำนาจในทางที่ผิด, ขาดความมั่นคง, ดื้อรั้น",
    meaning_rev: "Abuse of power, lack of stability, stubbornness",
    keywords: ["emperor", "throne"]
  },
  {
    name_en: "The Hierophant",
    name_th: "เดอะไฮโรแฟนท์",
    name: "The Hierophant",
    image: "/images/major_arcana_hierophant_result.webp",
    meaning_up_en: "Tradition, learning, guidance",
    meaning_up_th: "ประเพณี, การเรียนรู้, คำแนะนำ",
    meaning_up: "Tradition, learning, guidance",
    meaning_rev_en: "Rebelling against tradition, lack of guidance, misinformation",
    meaning_rev_th: "ต่อต้านประเพณี, ขาดคำแนะนำ, ความเชื่อผิด",
    meaning_rev: "Rebelling against tradition, lack of guidance, misinformation",
    keywords: ["priest", "religion"]
  },
  {
    name_en: "The Lovers",
    name_th: "เดอะเลิฟเวอร์ส",
    name: "The Lovers",
    image: "/images/major_arcana_lovers_result.webp",
    meaning_up_en: "Love, choice, relationships",
    meaning_up_th: "ความรัก, การเลือก, ความสัมพันธ์",
    meaning_up: "Love, choice, relationships",
    meaning_rev_en: "Conflict, wrong decision, unstable relationship",
    meaning_rev_th: "ความขัดแย้ง, การตัดสินใจผิด, ความสัมพันธ์ที่ไม่มั่นคง",
    meaning_rev: "Conflict, wrong decision, unstable relationship",
    keywords: ["lovers", "couple"]
  },
  {
    name_en: "The Chariot",
    name_th: "เดอะแชริออท",
    name: "The Chariot",
    image: "/images/major_arcana_chariot_result.webp",
    meaning_up_en: "Victory, control, determination",
    meaning_up_th: "ชัยชนะ, การควบคุม, ความมุ่งมั่น",
    meaning_up: "Victory, control, determination",
    meaning_rev_en: "Lack of control, failure, hesitation",
    meaning_rev_th: "ขาดการควบคุม, ความล้มเหลว, ความลังเล",
    meaning_rev: "Lack of control, failure, hesitation",
    keywords: ["chariot", "warrior"]
  },
  {
    name_en: "Strength",
    name_th: "สเตรงท์",
    name: "Strength",
    image: "/images/major_arcana_strength_result.webp",
    meaning_up_en: "Courage, patience, self-control",
    meaning_up_th: "ความกล้าหาญ, ความอดทน, การควบคุมตนเอง",
    meaning_up: "Courage, patience, self-control",
    meaning_rev_en: "Lack of confidence, weakness, lack of control",
    meaning_rev_th: "ขาดความมั่นใจ, อ่อนแอ, ขาดการควบคุม",
    meaning_rev: "Lack of confidence, weakness, lack of control",
    keywords: ["woman", "lion"]
  },
  {
    name_en: "The Hermit",
    name_th: "เดอะเฮอร์มิท",
    name: "The Hermit",
    image: "/images/major_arcana_hermit_result.webp",
    meaning_up_en: "Self-discovery, rest, contemplation",
    meaning_up_th: "การค้นหาตนเอง, การพักผ่อน, การไตร่ตรอง",
    meaning_up: "Self-discovery, rest, contemplation",
    meaning_rev_en: "Isolation, lack of contemplation, avoiding the truth",
    meaning_rev_th: "ความโดดเดี่ยว, ขาดการไตร่ตรอง, หลีกเลี่ยงความจริง",
    meaning_rev: "Isolation, lack of contemplation, avoiding the truth",
    keywords: ["hermit", "lantern"]
  },
  {
    name_en: "Wheel of Fortune",
    name_th: "วีลออฟฟอร์จูน",
    name: "Wheel of Fortune",
    image: "/images/major_arcana_fortune_result.webp",
    meaning_up_en: "Destiny, change, opportunity",
    meaning_up_th: "โชคชะตา, การเปลี่ยนแปลง, โอกาส",
    meaning_up: "Destiny, change, opportunity",
    meaning_rev_en: "Bad luck, clinging to the past, negative change",
    meaning_rev_th: "โชคร้าย, การติดอยู่กับอดีต, การเปลี่ยนแปลงที่ไม่ดี",
    meaning_rev: "Bad luck, clinging to the past, negative change",
    keywords: ["fortune", "wheel"]
  },
  {
    name_en: "Justice",
    name_th: "จัสติส",
    name: "Justice",
    image: "/images/major_arcana_justice_result.webp",
    meaning_up_en: "Justice, decision, truth",
    meaning_up_th: "ความยุติธรรม, การตัดสินใจ, ความจริง",
    meaning_up: "Justice, decision, truth",
    meaning_rev_en: "Injustice, wrong decision, avoiding responsibility",
    meaning_rev_th: "ความไม่ยุติธรรม, การตัดสินใจผิด, การหลีกเลี่ยงความรับผิดชอบ",
    meaning_rev: "Injustice, wrong decision, avoiding responsibility",
    keywords: ["justice", "scales"]
  },
  {
    name_en: "The Hanged Man",
    name_th: "เดอะแฮงด์แมน",
    name: "The Hanged Man",
    image: "/images/major_arcana_hanged_result.webp",
    meaning_up_en: "Sacrifice, new perspective, temporary halt",
    meaning_up_th: "การเสียสละ, การมองมุมใหม่, การหยุดชั่วคราว",
    meaning_up: "Sacrifice, new perspective, temporary halt",
    meaning_rev_en: "Lack of sacrifice, clinging to the past, unwillingness to change",
    meaning_rev_th: "ขาดการเสียสละ, ติดอยู่กับอดีต, ไม่ยอมเปลี่ยนแปลง",
    meaning_rev: "Lack of sacrifice, clinging to the past, unwillingness to change",
    keywords: ["hanged", "man"]
  },
  {
    name_en: "Death",
    name_th: "เดธ",
    name: "Death",
    image: "/images/major_arcana_death_result.webp",
    meaning_up_en: "End, change, rebirth",
    meaning_up_th: "การสิ้นสุด, การเปลี่ยนแปลง, การเกิดใหม่",
    meaning_up: "End, change, rebirth",
    meaning_rev_en: "Resisting change, fear, clinging to the past",
    meaning_rev_th: "ต่อต้านการเปลี่ยนแปลง, ความกลัว, การติดอยู่กับอดีต",
    meaning_rev: "Resisting change, fear, clinging to the past",
    keywords: ["grim", "reaper"]
  },
  {
    name_en: "Temperance",
    name_th: "เทมเพอแรนซ์",
    name: "Temperance",
    image: "/images/major_arcana_temperance_result.webp",
    meaning_up_en: "Balance, adaptation, patience",
    meaning_up_th: "ความสมดุล, การปรับตัว, ความอดทน",
    meaning_up: "Balance, adaptation, patience",
    meaning_rev_en: "Imbalance, extreme lifestyle, impatience",
    meaning_rev_th: "ขาดความสมดุล, การใช้ชีวิตสุดขั้ว, ขาดความอดทน",
    meaning_rev: "Imbalance, extreme lifestyle, impatience",
    keywords: ["angel", "water"]
  },
  {
    name_en: "The Devil",
    name_th: "เดอะเดวิล",
    name: "The Devil",
    image: "/images/major_arcana_devil_result.webp",
    meaning_up_en: "Limitation, addiction, passion",
    meaning_up_th: "ข้อจำกัด, การเสพติด, ความหลงใหล",
    meaning_up: "Limitation, addiction, passion",
    meaning_rev_en: "Liberation, release, awareness",
    meaning_rev_th: "การปลดปล่อย, การหลุดพ้น, การตระหนักรู้",
    meaning_rev: "Liberation, release, awareness",
    keywords: ["devil", "chains"]
  },
  {
    name_en: "The Tower",
    name_th: "เดอะทาวเวอร์",
    name: "The Tower",
    image: "/images/major_arcana_tower_result.webp",
    meaning_up_en: "Drastic change, collapse, truth revealed",
    meaning_up_th: "การเปลี่ยนแปลงอย่างรุนแรง, การล่มสลาย, การเปิดเผยความจริง",
    meaning_up: "Drastic change, collapse, truth revealed",
    meaning_rev_en: "Resisting change, fear, recovery",
    meaning_rev_th: "การต่อต้านการเปลี่ยนแปลง, ความกลัว, การฟื้นตัว",
    meaning_rev: "Resisting change, fear, recovery",
    keywords: ["tower", "lightning"]
  },
  {
    name_en: "The Star",
    name_th: "เดอะสตาร์",
    name: "The Star",
    image: "/images/major_arcana_star_result.webp",
    meaning_up_en: "Hope, healing, inspiration",
    meaning_up_th: "ความหวัง, การรักษา, แรงบันดาลใจ",
    meaning_up: "Hope, healing, inspiration",
    meaning_rev_en: "Hopelessness, disappointment, loss of inspiration",
    meaning_rev_th: "ขาดความหวัง, ความผิดหวัง, การสูญเสียแรงบันดาลใจ",
    meaning_rev: "Hopelessness, disappointment, loss of inspiration",
    keywords: ["woman", "star"]
  },
  {
    name_en: "The Moon",
    name_th: "เดอะมูน",
    name: "The Moon",
    image: "/images/major_arcana_moon_result.webp",
    meaning_up_en: "Mystery, intuition, dreams",
    meaning_up_th: "ความลึกลับ, สัญชาตญาณ, ความฝัน",
    meaning_up: "Mystery, intuition, dreams",
    meaning_rev_en: "Confusion, fear, deception",
    meaning_rev_th: "ความสับสน, ความกลัว, การหลอกลวง",
    meaning_rev: "Confusion, fear, deception",
    keywords: ["moon", "illusion"]
  },
  {
    name_en: "The Sun",
    name_th: "เดอะซัน",
    name: "The Sun",
    image: "/images/major_arcana_sun_result.webp",
    meaning_up_en: "Happiness, success, clarity",
    meaning_up_th: "ความสุข, ความสำเร็จ, ความชัดเจน",
    meaning_up: "Happiness, success, clarity",
    meaning_rev_en: "Disappointment, lack of happiness, failure",
    meaning_rev_th: "ความผิดหวัง, ขาดความสุข, ความล้มเหลว",
    meaning_rev: "Disappointment, lack of happiness, failure",
    keywords: ["sun", "child"]
  },
  {
    name_en: "Judgement",
    name_th: "จัดจ์เมนท์",
    name: "Judgement",
    image: "/images/major_arcana_judgement_result.webp",
    meaning_up_en: "Awakening, decision, resurrection",
    meaning_up_th: "การตื่นรู้, การตัดสินใจ, การฟื้นคืนชีพ",
    meaning_up: "Awakening, decision, resurrection",
    meaning_rev_en: "Wrong decision, lack of awakening, clinging to the past",
    meaning_rev_th: "การตัดสินใจผิด, ขาดการตื่นรู้, การติดอยู่กับอดีต",
    meaning_rev: "Wrong decision, lack of awakening, clinging to the past",
    keywords: ["angel", "resurrection"]
  },
  {
    name_en: "The World",
    name_th: "เดอะเวิลด์",
    name: "The World",
    image: "/images/major_arcana_world_result.webp",
    meaning_up_en: "Success, achievement, completion",
    meaning_up_th: "ความสำเร็จ, การบรรลุเป้าหมาย, การเดินทางครบวงจร",
    meaning_up: "Success, achievement, completion",
    meaning_rev_en: "Lack of success, clinging to the past, unfinished journey",
    meaning_rev_th: "ขาดความสำเร็จ, การติดอยู่กับอดีต, การเดินทางที่ยังไม่จบ",
    meaning_rev: "Lack of success, clinging to the past, unfinished journey",
    keywords: ["world", "dancer"]
  },

  // MINOR ARCANA - CUPS (14 cards)
  {
    name_en: "Ace of Cups",
    name_th: "เอซ ออฟ คัพส์",
    name: "Ace of Cups",
    image: "/images/minor_arcana_cups_ace_result.webp",
    meaning_up_en: "New love, emotional renewal, spiritual awakening",
    meaning_up_th: "ความรักใหม่, การฟื้นฟูทางอารมณ์, การตื่นรู้ทางจิตวิญญาณ",
    meaning_up: "New love, emotional renewal, spiritual awakening",
    meaning_rev_en: "Emotional loss, blocked creativity, emptiness",
    meaning_rev_th: "การสูญเสียทางอารมณ์, ความคิดสร้างสรรค์ถูกขัดขวาง, ความว่างเปล่า",
    meaning_rev: "Emotional loss, blocked creativity, emptiness",
    keywords: ["cup", "new", "emotion"]
  },
  {
    name_en: "Two of Cups",
    name_th: "ทู ออฟ คัพส์",
    name: "Two of Cups",
    image: "/images/minor_arcana_cups_2_result.webp",
    meaning_up_en: "Partnership, mutual attraction, unity",
    meaning_up_th: "ความเป็นหุ้นส่วน, การดึงดูดซึ่งกันและกัน, ความเป็นอันหนึ่งอันเดียว",
    meaning_up: "Partnership, mutual attraction, unity",
    meaning_rev_en: "Imbalance, broken relationship, lack of harmony",
    meaning_rev_th: "ความไม่สมดุล, ความสัมพันธ์ที่แตกสลาย, ขาดความสามัคคี",
    meaning_rev: "Imbalance, broken relationship, lack of harmony",
    keywords: ["partnership", "love", "union"]
  },
  {
    name_en: "Three of Cups",
    name_th: "ทรี ออฟ คัพส์",
    name: "Three of Cups",
    image: "/images/minor_arcana_cups_3_result.webp",
    meaning_up_en: "Celebration, friendship, community",
    meaning_up_th: "การเฉลิมฉลอง, มิตรภาพ, ชุมชน",
    meaning_up: "Celebration, friendship, community",
    meaning_rev_en: "Isolation, loneliness, overindulgence",
    meaning_rev_th: "การแยกตัว, ความเหงา, การหลงระเริง",
    meaning_rev: "Isolation, loneliness, overindulgence",
    keywords: ["celebration", "friends", "joy"]
  },
  {
    name_en: "Four of Cups",
    name_th: "โฟร์ ออฟ คัพส์",
    name: "Four of Cups",
    image: "/images/minor_arcana_cups_4_result.webp",
    meaning_up_en: "Contemplation, apathy, boredom",
    meaning_up_th: "การไตร่ตรอง, ความเฉยเมย, ความเบื่อหน่าย",
    meaning_up: "Contemplation, apathy, boredom",
    meaning_rev_en: "Sudden awareness, new opportunities, acceptance",
    meaning_rev_th: "การตระหนักรู้อย่างกะทันหัน, โอกาสใหม่, การยอมรับ",
    meaning_rev: "Sudden awareness, new opportunities, acceptance",
    keywords: ["meditation", "withdrawal", "introspection"]
  },
  {
    name_en: "Five of Cups",
    name_th: "ไฟว์ ออฟ คัพส์",
    name: "Five of Cups",
    image: "/images/minor_arcana_cups_5_result.webp",
    meaning_up_en: "Loss, grief, disappointment",
    meaning_up_th: "การสูญเสีย, ความเศร้าโศก, ความผิดหวัง",
    meaning_up: "Loss, grief, disappointment",
    meaning_rev_en: "Acceptance, moving on, finding peace",
    meaning_rev_th: "การยอมรับ, การก้าวต่อไป, การค้นหาความสงบ",
    meaning_rev: "Acceptance, moving on, finding peace",
    keywords: ["grief", "loss", "regret"]
  },
  {
    name_en: "Six of Cups",
    name_th: "ซิกซ์ ออฟ คัพส์",
    name: "Six of Cups",
    image: "/images/minor_arcana_cups_6_result.webp",
    meaning_up_en: "Nostalgia, childhood memories, innocence",
    meaning_up_th: "ความคิดถึง, ความทรงจำวัยเด็ก, ความบริสุทธิ์",
    meaning_up: "Nostalgia, childhood memories, innocence",
    meaning_rev_en: "Living in the past, unrealistic expectations, immaturity",
    meaning_rev_th: "การใช้ชีวิตในอดีต, ความคาดหวังที่ไม่สมจริง, ความไม่เป็นผู้ใหญ่",
    meaning_rev: "Living in the past, unrealistic expectations, immaturity",
    keywords: ["nostalgia", "past", "childhood"]
  },
  {
    name_en: "Seven of Cups",
    name_th: "เซเว่น ออฟ คัพส์",
    name: "Seven of Cups",
    image: "/images/minor_arcana_cups_7_result.webp",
    meaning_up_en: "Illusion, choices, wishful thinking",
    meaning_up_th: "ภาพลวงตา, ทางเลือก, ความปรารถนาที่ไร้เหตุผล",
    meaning_up: "Illusion, choices, wishful thinking",
    meaning_rev_en: "Clarity, determination, making decisions",
    meaning_rev_th: "ความชัดเจน, ความมุ่งมั่น, การตัดสินใจ",
    meaning_rev: "Clarity, determination, making decisions",
    keywords: ["illusion", "fantasy", "options"]
  },
  {
    name_en: "Eight of Cups",
    name_th: "เอท ออฟ คัพส์",
    name: "Eight of Cups",
    image: "/images/minor_arcana_cups_8_result.webp",
    meaning_up_en: "Abandonment, walking away, spiritual quest",
    meaning_up_th: "การทอดทิ้ง, การเดินจากไป, การแสวงหาทางจิตวิญญาณ",
    meaning_up: "Abandonment, walking away, spiritual quest",
    meaning_rev_en: "Fear of change, staying in bad situation, avoidance",
    meaning_rev_th: "ความกลัวการเปลี่ยนแปลง, การอยู่ในสถานการณ์ที่ไม่ดี, การหลีกเลี่ยง",
    meaning_rev: "Fear of change, staying in bad situation, avoidance",
    keywords: ["departure", "abandonment", "search"]
  },
  {
    name_en: "Nine of Cups",
    name_th: "ไนน์ ออฟ คัพส์",
    name: "Nine of Cups",
    image: "/images/minor_arcana_cups_9_result.webp",
    meaning_up_en: "Contentment, satisfaction, wish fulfillment",
    meaning_up_th: "ความพอใจ, ความพึงพอใจ, ความปรารถนาที่เป็นจริง",
    meaning_up: "Contentment, satisfaction, wish fulfillment",
    meaning_rev_en: "Greed, materialism, false happiness",
    meaning_rev_th: "ความโลภ, การบูชาวัตถุ, ความสุขที่เท็จ",
    meaning_rev: "Greed, materialism, false happiness",
    keywords: ["satisfaction", "contentment", "wishes"]
  },
  {
    name_en: "Ten of Cups",
    name_th: "เทน ออฟ คัพส์",
    name: "Ten of Cups",
    image: "/images/minor_arcana_cups_10_result.webp",
    meaning_up_en: "Happiness, family harmony, emotional fulfillment",
    meaning_up_th: "ความสุข, ความสามัคคีในครอบครัว, ความพึงพอใจทางอารมณ์",
    meaning_up: "Happiness, family harmony, emotional fulfillment",
    meaning_rev_en: "Family problems, disharmony, broken relationships",
    meaning_rev_th: "ปัญหาครอบครัว, ความไม่สามัคคี, ความสัมพันธ์ที่แตกสลาย",
    meaning_rev: "Family problems, disharmony, broken relationships",
    keywords: ["family", "happiness", "harmony"]
  },
  {
    name_en: "Page of Cups",
    name_th: "เพจ ออฟ คัพส์",
    name: "Page of Cups",
    image: "/images/minor_arcana_cups_page_result.webp",
    meaning_up_en: "Creative beginnings, intuitive messages, emotional sensitivity",
    meaning_up_th: "การเริ่มต้นสร้างสรรค์, ข้อความจากสัญชาตญาณ, ความไวทางอารมณ์",
    meaning_up: "Creative beginnings, intuitive messages, emotional sensitivity",
    meaning_rev_en: "Emotional immaturity, escapism, unrealistic dreams",
    meaning_rev_th: "ความไม่เป็นผู้ใหญ่ทางอารมณ์, การหลบหนีความจริง, ความฝันที่ไม่สมจริง",
    meaning_rev: "Emotional immaturity, escapism, unrealistic dreams",
    keywords: ["youth", "creativity", "intuition"]
  },
  {
    name_en: "Knight of Cups",
    name_th: "ไนท์ ออฟ คัพส์",
    name: "Knight of Cups",
    image: "/images/minor_arcana_cups_knight_result.webp",
    meaning_up_en: "Romance, charm, following your heart",
    meaning_up_th: "ความโรแมนติก, เสน่ห์, การทำตามใจ",
    meaning_up: "Romance, charm, following your heart",
    meaning_rev_en: "Moodiness, unrealistic expectations, jealousy",
    meaning_rev_th: "ความเปลี่ยนแปลงอารมณ์, ความคาดหวังที่ไม่สมจริง, ความหึงหวง",
    meaning_rev: "Moodiness, unrealistic expectations, jealousy",
    keywords: ["romance", "idealism", "emotion"]
  },
  {
    name_en: "Queen of Cups",
    name_th: "ควีน ออฟ คัพส์",
    name: "Queen of Cups",
    image: "/images/minor_arcana_cups_queen_result.webp",
    meaning_up_en: "Emotional security, intuitive, compassionate",
    meaning_up_th: "ความมั่นคงทางอารมณ์, สัญชาตญาณ, ความเมตตา",
    meaning_up: "Emotional security, intuitive, compassionate",
    meaning_rev_en: "Emotional insecurity, co-dependency, martyrdom",
    meaning_rev_th: "ความไม่มั่นคงทางอารมณ์, การพึ่งพาอาศัยกัน, การเสียสละแบบไม่เหมาะสม",
    meaning_rev: "Emotional insecurity, co-dependency, martyrdom",
    keywords: ["compassion", "intuition", "emotional"]
  },
  {
    name_en: "King of Cups",
    name_th: "คิง ออฟ คัพส์",
    name: "King of Cups",
    image: "/images/minor_arcana_cups_king_result.webp",
    meaning_up_en: "Emotional control, wisdom, diplomacy",
    meaning_up_th: "การควบคุมอารมณ์, ปัญญา, การทูต",
    meaning_up: "Emotional control, wisdom, diplomacy",
    meaning_rev_en: "Emotional manipulation, moodiness, lack of empathy",
    meaning_rev_th: "การจัดการอารมณ์แบบผิดๆ, ความเปลี่ยนแปลงอารมณ์, ขาดความเห็นอกเห็นใจ",
    meaning_rev: "Emotional manipulation, moodiness, lack of empathy",
    keywords: ["wisdom", "control", "diplomatic"]
  },

  // MINOR ARCANA - WANDS (14 cards)
  {
    name_en: "Ace of Wands",
    name_th: "เอซ ออฟ แวนด์ส",
    name: "Ace of Wands",
    image: "/images/minor_arcana_wands_ace_result.webp",
    meaning_up_en: "New beginnings, creative energy, inspiration",
    meaning_up_th: "การเริ่มต้นใหม่, พลังความคิดสร้างสรรค์, แรงบันดาลใจ",
    meaning_up: "New beginnings, creative energy, inspiration",
    meaning_rev_en: "Lack of energy, delays, false starts",
    meaning_rev_th: "ขาดพลังงาน, ความล่าช้า, การเริ่มต้นที่ผิดพลาด",
    meaning_rev: "Lack of energy, delays, false starts",
    keywords: ["wand", "new", "creative"]
  },
  {
    name_en: "Two of Wands",
    name_th: "ทู ออฟ แวนด์ส",
    name: "Two of Wands",
    image: "/images/minor_arcana_wands_2_result.webp",
    meaning_up_en: "Planning, making decisions, personal power",
    meaning_up_th: "การวางแผน, การตัดสินใจ, อำนาจส่วนบุคคล",
    meaning_up: "Planning, making decisions, personal power",
    meaning_rev_en: "Lack of planning, disorganized, fear of unknown",
    meaning_rev_th: "ขาดการวางแผน, ไม่เป็นระเบียบ, ความกลัวต่อสิ่งที่ไม่รู้",
    meaning_rev: "Lack of planning, disorganized, fear of unknown",
    keywords: ["planning", "decisions", "control"]
  },
  {
    name_en: "Three of Wands",
    name_th: "ทรี ออฟ แวนด์ส",
    name: "Three of Wands",
    image: "/images/minor_arcana_wands_3_result.webp",
    meaning_up_en: "Expansion, foresight, overseas opportunities",
    meaning_up_th: "การขยายตัว, การมองการณ์ไกล, โอกาสต่างประเทศ",
    meaning_up: "Expansion, foresight, overseas opportunities",
    meaning_rev_en: "Lack of foresight, delays, obstacles",
    meaning_rev_th: "ขาดการมองการณ์ไกล, ความล่าช้า, อุปสรรค",
    meaning_rev: "Lack of foresight, delays, obstacles",
    keywords: ["expansion", "exploration", "foresight"]
  },
  {
    name_en: "Four of Wands",
    name_th: "โฟร์ ออฟ แวนด์ส",
    name: "Four of Wands",
    image: "/images/minor_arcana_wands_4_result.webp",
    meaning_up_en: "Celebration, harmony, homecoming",
    meaning_up_th: "การเฉลิมฉลอง, ความสามัคคี, การกลับบ้าน",
    meaning_up: "Celebration, harmony, homecoming",
    meaning_rev_en: "Lack of support, instability, tensions",
    meaning_rev_th: "ขาดการสนับสนุน, ความไม่มั่นคง, ความตึงเครียด",
    meaning_rev: "Lack of support, instability, tensions",
    keywords: ["celebration", "community", "stability"]
  },
  {
    name_en: "Five of Wands",
    name_th: "ไฟว์ ออฟ แวนด์ส",
    name: "Five of Wands",
    image: "/images/minor_arcana_wands_5_result.webp",
    meaning_up_en: "Competition, conflict, rivalry",
    meaning_up_th: "การแข่งขัน, ความขัดแย้ง, การแข่งแย่ง",
    meaning_up: "Competition, conflict, rivalry",
    meaning_rev_en: "Avoiding conflict, cooperation, inner conflict",
    meaning_rev_th: "การหลีกเลี่ยงความขัดแย้ง, ความร่วมมือ, ความขัดแย้งภายใน",
    meaning_rev: "Avoiding conflict, cooperation, inner conflict",
    keywords: ["conflict", "competition", "struggle"]
  },
  {
    name_en: "Six of Wands",
    name_th: "ซิกซ์ ออฟ แวนด์ส",
    name: "Six of Wands",
    image: "/images/minor_arcana_wands_6_result.webp",
    meaning_up_en: "Victory, success, public recognition",
    meaning_up_th: "ชัยชนะ, ความสำเร็จ, การได้รับการยอมรับจากสาธารณะ",
    meaning_up: "Victory, success, public recognition",
    meaning_rev_en: "Private achievement, lack of recognition, delays",
    meaning_rev_th: "ความสำเร็จส่วนตัว, ขาดการยอมรับ, ความล่าช้า",
    meaning_rev: "Private achievement, lack of recognition, delays",
    keywords: ["victory", "success", "recognition"]
  },
  {
    name_en: "Seven of Wands",
    name_th: "เซเว่น ออฟ แวนด์ส",
    name: "Seven of Wands",
    image: "/images/minor_arcana_wands_7_result.webp",
    meaning_up_en: "Perseverance, defensive, maintaining position",
    meaning_up_th: "ความอดทน, การป้องกัน, การรักษาตำแหน่ง",
    meaning_up: "Perseverance, defensive, maintaining position",
    meaning_rev_en: "Giving up, admitting defeat, overwhelmed",
    meaning_rev_th: "การยอมแพ้, การยอมรับความพ่ายแพ้, ความถูกครอบงำ",
    meaning_rev: "Giving up, admitting defeat, overwhelmed",
    keywords: ["perseverance", "defense", "challenge"]
  },
  {
    name_en: "Eight of Wands",
    name_th: "เอท ออฟ แวนด์ส",
    name: "Eight of Wands",
    image: "/images/minor_arcana_wands_8_result.webp",
    meaning_up_en: "Speed, rapid action, movement",
    meaning_up_th: "ความเร็ว, การกระทำอย่างรวดเร็ว, การเคลื่อนไหว",
    meaning_up: "Speed, rapid action, movement",
    meaning_rev_en: "Delays, frustration, resisting change",
    meaning_rev_th: "ความล่าช้า, ความยุ่งยาก, การต่อต้านการเปลี่ยนแปลง",
    meaning_rev: "Delays, frustration, resisting change",
    keywords: ["speed", "action", "progress"]
  },
  {
    name_en: "Nine of Wands",
    name_th: "ไนน์ ออฟ แวนด์ส",
    name: "Nine of Wands",
    image: "/images/minor_arcana_wands_9_result.webp",
    meaning_up_en: "Resilience, courage, last stand",
    meaning_up_th: "ความยืดหยุ่น, ความกล้าหาญ, การต่อสู้ครั้งสุดท้าย",
    meaning_up: "Resilience, courage, last stand",
    meaning_rev_en: "Exhaustion, giving up, paranoia",
    meaning_rev_th: "ความเหนื่อยล้า, การยอมแพ้, อาการหวาดระแวง",
    meaning_rev: "Exhaustion, giving up, paranoia",
    keywords: ["resilience", "persistence", "strength"]
  },
  {
    name_en: "Ten of Wands",
    name_th: "เทน ออฟ แวนด์ส",
    name: "Ten of Wands",
    image: "/images/minor_arcana_wands_10_result.webp",
    meaning_up_en: "Burden, hard work, accomplishment",
    meaning_up_th: "ภาระ, การทำงานหนัก, ความสำเร็จ",
    meaning_up: "Burden, hard work, accomplishment",
    meaning_rev_en: "Delegation, releasing burdens, working smarter",
    meaning_rev_th: "การมอบหมาย, การปลดปล่อยภาระ, การทำงานอย่างฉลาด",
    meaning_rev: "Delegation, releasing burdens, working smarter",
    keywords: ["burden", "responsibility", "completion"]
  },
  {
    name_en: "Page of Wands",
    name_th: "เพจ ออฟ แวนด์ส",
    name: "Page of Wands",
    image: "/images/minor_arcana_wands_page_result.webp",
    meaning_up_en: "Enthusiasm, exploration, discovery",
    meaning_up_th: "ความกระตือรือร้น, การสำรวจ, การค้นพบ",
    meaning_up: "Enthusiasm, exploration, discovery",
    meaning_rev_en: "Lack of direction, procrastination, impatience",
    meaning_rev_th: "ขาดทิศทาง, การผัดวันประกันพรุ่ง, ความใจร้อน",
    meaning_rev: "Lack of direction, procrastination, impatience",
    keywords: ["enthusiasm", "adventure", "discovery"]
  },
  {
    name_en: "Knight of Wands",
    name_th: "ไนท์ ออฟ แวนด์ส",
    name: "Knight of Wands",
    image: "/images/minor_arcana_wands_knight_result.webp",
    meaning_up_en: "Impulsiveness, adventure, recklessness",
    meaning_up_th: "ความหุนหันพลันแล่น, การผจญภัย, ความประมาท",
    meaning_up: "Impulsiveness, adventure, recklessness",
    meaning_rev_en: "Haste, scattered energy, frustration",
    meaning_rev_th: "ความรีบร้อน, พลังงานที่กระจาย, ความยุ่งยาก",
    meaning_rev: "Haste, scattered energy, frustration",
    keywords: ["adventure", "impulsive", "energy"]
  },
  {
    name_en: "Queen of Wands",
    name_th: "ควีน ออฟ แวนด์ส",
    name: "Queen of Wands",
    image: "/images/minor_arcana_wands_queen_result.webp",
    meaning_up_en: "Confidence, independence, determination",
    meaning_up_th: "ความมั่นใจ, ความเป็นอิสระ, ความมุ่งมั่น",
    meaning_up: "Confidence, independence, determination",
    meaning_rev_en: "Self-doubt, jealousy, insecurity",
    meaning_rev_th: "ความสงสัยในตนเอง, ความหึงหวง, ความไม่มั่นคง",
    meaning_rev: "Self-doubt, jealousy, insecurity",
    keywords: ["confidence", "independence", "warmth"]
  },
  {
    name_en: "King of Wands",
    name_th: "คิง ออฟ แวนด์ส",
    name: "King of Wands",
    image: "/images/minor_arcana_wands_king_result.webp",
    meaning_up_en: "Leadership, vision, entrepreneurship",
    meaning_up_th: "ความเป็นผู้นำ, วิสัยทัศน์, การเป็นผู้ประกอบการ",
    meaning_up: "Leadership, vision, entrepreneurship",
    meaning_rev_en: "Tyranny, arrogance, impulsiveness",
    meaning_rev_th: "การเป็นทรราช, ความเย่อหยิ่ง, ความหุนหันพลันแล่น",
    meaning_rev: "Tyranny, arrogance, impulsiveness",
    keywords: ["leadership", "vision", "charisma"]
  },

  // MINOR ARCANA - SWORDS (14 cards)
  {
    name_en: "Ace of Swords",
    name_th: "เอซ ออฟ ซอร์ดส์",
    name: "Ace of Swords",
    image: "/images/minor_arcana_swords_ace_result.webp",
    meaning_up_en: "New ideas, mental clarity, breakthrough",
    meaning_up_th: "ความคิดใหม่, ความชัดเจนทางจิตใจ, การทะลุทะลวง",
    meaning_up: "New ideas, mental clarity, breakthrough",
    meaning_rev_en: "Mental confusion, chaos, lack of clarity",
    meaning_rev_th: "ความสับสนทางจิตใจ, ความวุ่นวาย, ขาดความชัดเจน",
    meaning_rev: "Mental confusion, chaos, lack of clarity",
    keywords: ["sword", "clarity", "breakthrough"]
  },
  {
    name_en: "Two of Swords",
    name_th: "ทู ออฟ ซอร์ดส์",
    name: "Two of Swords",
    image: "/images/minor_arcana_swords_2_result.webp",
    meaning_up_en: "Difficult decisions, weighing options, stalemate",
    meaning_up_th: "การตัดสินใจที่ยาก, การชั่งน้ำหนักตัวเลือก, ความจนมุม",
    meaning_up: "Difficult decisions, weighing options, stalemate",
    meaning_rev_en: "Indecision, confusion, information overload",
    meaning_rev_th: "ความลังเลใจ, ความสับสน, ข้อมูลล้นหลาม",
    meaning_rev: "Indecision, confusion, information overload",
    keywords: ["decisions", "balance", "stalemate"]
  },
  {
    name_en: "Three of Swords",
    name_th: "ทรี ออฟ ซอร์ดส์",
    name: "Three of Swords",
    image: "/images/minor_arcana_swords_3_result.webp",
    meaning_up_en: "Heartbreak, sorrow, betrayal",
    meaning_up_th: "ใจสลาย, ความเศร้าโศก, การทรยศ",
    meaning_up: "Heartbreak, sorrow, betrayal",
    meaning_rev_en: "Recovery, forgiveness, moving on",
    meaning_rev_th: "การฟื้นตัว, การให้อภัย, การก้าวต่อไป",
    meaning_rev: "Recovery, forgiveness, moving on",
    keywords: ["heartbreak", "sorrow", "pain"]
  },
  {
    name_en: "Four of Swords",
    name_th: "โฟร์ ออฟ ซอร์ดส์",
    name: "Four of Swords",
    image: "/images/minor_arcana_swords_4_result.webp",
    meaning_up_en: "Rest, contemplation, recovery",
    meaning_up_th: "การพักผ่อน, การไตร่ตรอง, การฟื้นตัว",
    meaning_up: "Rest, contemplation, recovery",
    meaning_rev_en: "Restlessness, burnout, stress",
    meaning_rev_th: "ความไม่สงบ, ความเหนื่อยล้า, ความเครียด",
    meaning_rev: "Restlessness, burnout, stress",
    keywords: ["rest", "meditation", "peace"]
  },
  {
    name_en: "Five of Swords",
    name_th: "ไฟว์ ออฟ ซอร์ดส์",
    name: "Five of Swords",
    image: "/images/minor_arcana_swords_5_result.webp",
    meaning_up_en: "Defeat, betrayal, winning at all costs",
    meaning_up_th: "ความพ่ายแพ้, การทรยศ, การชนะไม่ว่าจะต้องเสียอะไร",
    meaning_up: "Defeat, betrayal, winning at all costs",
    meaning_rev_en: "Making amends, forgiveness, moving past conflict",
    meaning_rev_th: "การชดเชย, การให้อภัย, การก้าวผ่านความขัดแย้ง",
    meaning_rev: "Making amends, forgiveness, moving past conflict",
    keywords: ["defeat", "conflict", "betrayal"]
  },
  {
    name_en: "Six of Swords",
    name_th: "ซิกซ์ ออฟ ซอร์ดส์",
    name: "Six of Swords",
    image: "/images/minor_arcana_swords_6_result.webp",
    meaning_up_en: "Transition, moving forward, leaving the past",
    meaning_up_th: "การเปลี่ยนผ่าน, การก้าวไปข้างหน้า, การทิ้งอดีต",
    meaning_up: "Transition, moving forward, leaving the past",
    meaning_rev_en: "Stuck in the past, resistance to change, unfinished business",
    meaning_rev_th: "ติดอยู่ในอดีต, การต่อต้านการเปลี่ยนแปลง, ธุรกิจที่ยังไม่เสร็จ",
    meaning_rev: "Stuck in the past, resistance to change, unfinished business",
    keywords: ["transition", "journey", "moving"]
  },
  {
    name_en: "Seven of Swords",
    name_th: "เซเว่น ออฟ ซอร์ดส์",
    name: "Seven of Swords",
    image: "/images/minor_arcana_swords_7_result.webp",
    meaning_up_en: "Deception, theft, getting away with something",
    meaning_up_th: "การหลอกลวง, การขโมย, การรอดพ้นจากบางสิ่ง",
    meaning_up: "Deception, theft, getting away with something",
    meaning_rev_en: "Getting caught, confession, coming clean",
    meaning_rev_th: "ถูกจับได้, การสารภาพ, การพูดความจริง",
    meaning_rev: "Getting caught, confession, coming clean",
    keywords: ["deception", "strategy", "theft"]
  },
  {
    name_en: "Eight of Swords",
    name_th: "เอท ออฟ ซอร์ดส์",
    name: "Eight of Swords",
    image: "/images/minor_arcana_swords_8_result.webp",
    meaning_up_en: "Restriction, imprisonment, victimization",
    meaning_up_th: "ข้อจำกัด, การถูกจำคุก, การเป็นเหยื่อ",
    meaning_up: "Restriction, imprisonment, victimization",
    meaning_rev_en: "Freedom, release, self-empowerment",
    meaning_rev_th: "อิสรภาพ, การปลดปล่อย, การเสริมสร้างพลังตนเอง",
    meaning_rev: "Freedom, release, self-empowerment",
    keywords: ["restriction", "trapped", "limitation"]
  },
  {
    name_en: "Nine of Swords",
    name_th: "ไนน์ ออฟ ซอร์ดส์",
    name: "Nine of Swords",
    image: "/images/minor_arcana_swords_9_result.webp",
    meaning_up_en: "Anxiety, worry, nightmares",
    meaning_up_th: "ความวิตกกังวล, ความกังวล, ฝันร้าย",
    meaning_up: "Anxiety, worry, nightmares",
    meaning_rev_en: "Hope, recovery, seeking help",
    meaning_rev_th: "ความหวัง, การฟื้นตัว, การขอความช่วยเหลือ",
    meaning_rev: "Hope, recovery, seeking help",
    keywords: ["anxiety", "worry", "nightmares"]
  },
  {
    name_en: "Ten of Swords",
    name_th: "เทน ออฟ ซอร์ดส์",
    name: "Ten of Swords",
    image: "/images/minor_arcana_swords_10_result.webp",
    meaning_up_en: "Rock bottom, betrayal, painful endings",
    meaning_up_th: "จุดต่ำสุด, การทรยศ, การจบที่เจ็บปวด",
    meaning_up: "Rock bottom, betrayal, painful endings",
    meaning_rev_en: "Recovery, regeneration, resisting ruin",
    meaning_rev_th: "การฟื้นตัว, การฟื้นฟู, การต่อต้านการทำลาย",
    meaning_rev: "Recovery, regeneration, resisting ruin",
    keywords: ["ending", "betrayal", "ruin"]
  },
  {
    name_en: "Page of Swords",
    name_th: "เพจ ออฟ ซอร์ดส์",
    name: "Page of Swords",
    image: "/images/minor_arcana_swords_page_result.webp",
    meaning_up_en: "Curiosity, restlessness, new ideas",
    meaning_up_th: "ความอยากรู้, ความไม่สงบ, ความคิดใหม่",
    meaning_up: "Curiosity, restlessness, new ideas",
    meaning_rev_en: "Scatterbrained, hasty, unfocused",
    meaning_rev_th: "สมองกระจัดกระจาย, รีบร้อน, ไม่มีสมาธิ",
    meaning_rev: "Scatterbrained, hasty, unfocused",
    keywords: ["curiosity", "communication", "vigilance"]
  },
  {
    name_en: "Knight of Swords",
    name_th: "ไนท์ ออฟ ซอร์ดส์",
    name: "Knight of Swords",
    image: "/images/minor_arcana_swords_knight_result.webp",
    meaning_up_en: "Ambition, driven, fast thinking",
    meaning_up_th: "ความทะเยอทะยาน, การถูกขับเคลื่อน, การคิดเร็ว",
    meaning_up: "Ambition, driven, fast thinking",
    meaning_rev_en: "Reckless, impatient, unfocused",
    meaning_rev_th: "ประมาท, ใจร้อน, ไม่มีสมาธิ",
    meaning_rev: "Reckless, impatient, unfocused",
    keywords: ["ambition", "action", "driven"]
  },
  {
    name_en: "Queen of Swords",
    name_th: "ควีน ออฟ ซอร์ดส์",
    name: "Queen of Swords",
    image: "/images/minor_arcana_swords_queen_result.webp",
    meaning_up_en: "Independent, direct communication, intellectual",
    meaning_up_th: "เป็นอิสระ, สื่อสารตรงไปตรงมา, มีเหตุผล",
    meaning_up: "Independent, direct communication, intellectual",
    meaning_rev_en: "Cold-hearted, cruel, bitterness",
    meaning_rev_th: "ใจแข็ง, โหดร้าย, ขมขื่น",
    meaning_rev: "Cold-hearted, cruel, bitterness",
    keywords: ["independent", "intellectual", "truth"]
  },
  {
    name_en: "King of Swords",
    name_th: "คิง ออฟ ซอร์ดส์",
    name: "King of Swords",
    image: "/images/minor_arcana_swords_king_result.webp",
    meaning_up_en: "Logical, authority, truth",
    meaning_up_th: "มีเหตุผล, มีอำนาจ, ความจริง",
    meaning_up: "Logical, authority, truth",
    meaning_rev_en: "Tyrannical, abusive, harsh",
    meaning_rev_th: "เผด็จการ, ใช้อำนาจในทางที่ผิด, โหดร้าย",
    meaning_rev: "Tyrannical, abusive, harsh",
    keywords: ["logic", "authority", "clarity"]
  },

  // MINOR ARCANA - PENTACLES (14 cards)
  {
    name_en: "Ace of Pentacles",
    name_th: "เอซ ออฟ เพนทาเคิลส์",
    name: "Ace of Pentacles",
    image: "/images/minor_arcana_pentacles_ace_result.webp",
    meaning_up_en: "New financial opportunity, prosperity, abundance",
    meaning_up_th: "โอกาสทางการเงินใหม่, ความมั่งคั่ง, ความอุดมสมบูรณ์",
    meaning_up: "New financial opportunity, prosperity, abundance",
    meaning_rev_en: "Missed opportunity, financial loss, scarcity",
    meaning_rev_th: "พลาดโอกาส, การสูญเสียทางการเงิน, ความขาดแคลน",
    meaning_rev: "Missed opportunity, financial loss, scarcity",
    keywords: ["prosperity", "abundance", "opportunity"]
  },
  {
    name_en: "Two of Pentacles",
    name_th: "ทู ออฟ เพนทาเคิลส์",
    name: "Two of Pentacles",
    image: "/images/minor_arcana_pentacles_2_result.webp",
    meaning_up_en: "Balance, adaptability, juggling priorities",
    meaning_up_th: "ความสมดุล, การปรับตัว, การจัดการหลายสิ่ง",
    meaning_up: "Balance, adaptability, juggling priorities",
    meaning_rev_en: "Imbalance, disorganization, overwhelmed",
    meaning_rev_th: "ไม่สมดุล, ไร้ระเบียบ, ถูกครอบงำ",
    meaning_rev: "Imbalance, disorganization, overwhelmed",
    keywords: ["balance", "priorities", "adaptation"]
  },
  {
    name_en: "Three of Pentacles",
    name_th: "ทรี ออฟ เพนทาเคิลส์",
    name: "Three of Pentacles",
    image: "/images/minor_arcana_pentacles_3_result.webp",
    meaning_up_en: "Teamwork, collaboration, learning",
    meaning_up_th: "การทำงานเป็นทีม, ความร่วมมือ, การเรียนรู้",
    meaning_up: "Teamwork, collaboration, learning",
    meaning_rev_en: "Lack of teamwork, disorganized, lack of skill",
    meaning_rev_th: "ขาดการทำงานเป็นทีม, ไร้ระเบียบ, ขาดทักษะ",
    meaning_rev: "Lack of teamwork, disorganized, lack of skill",
    keywords: ["teamwork", "collaboration", "skill"]
  },
  {
    name_en: "Four of Pentacles",
    name_th: "โฟร์ ออฟ เพนทาเคิลส์",
    name: "Four of Pentacles",
    image: "/images/minor_arcana_pentacles_4_result.webp",
    meaning_up_en: "Security, control, conservatism",
    meaning_up_th: "ความมั่นคง, การควบคุม, ความอนุรักษ์นิยม",
    meaning_up: "Security, control, conservatism",
    meaning_rev_en: "Greed, materialism, insecurity",
    meaning_rev_th: "ความโลภ, วัตถุนิยม, ความไม่มั่นคง",
    meaning_rev: "Greed, materialism, insecurity",
    keywords: ["security", "possession", "conservation"]
  },
  {
    name_en: "Five of Pentacles",
    name_th: "ไฟว์ ออฟ เพนทาเคิลส์",
    name: "Five of Pentacles",
    image: "/images/minor_arcana_pentacles_5_result.webp",
    meaning_up_en: "Hardship, poverty, insecurity",
    meaning_up_th: "ความยากลำบาก, ความยากจน, ความไม่มั่นคง",
    meaning_up: "Hardship, poverty, insecurity",
    meaning_rev_en: "Recovery, spiritual growth, support",
    meaning_rev_th: "การฟื้นตัว, การเติบโตทางจิตวิญญาณ, การสนับสนุน",
    meaning_rev: "Recovery, spiritual growth, support",
    keywords: ["hardship", "poverty", "isolation"]
  },
  {
    name_en: "Six of Pentacles",
    name_th: "ซิกซ์ ออฟ เพนทาเคิลส์",
    name: "Six of Pentacles",
    image: "/images/minor_arcana_pentacles_6_result.webp",
    meaning_up_en: "Generosity, charity, sharing",
    meaning_up_th: "ความเอื้อเฟื้อ, การบริจาค, การแบ่งปัน",
    meaning_up: "Generosity, charity, sharing",
    meaning_rev_en: "Selfishness, debt, unbalanced giving",
    meaning_rev_th: "ความเห็นแก่ตัว, หนี้สิน, การให้ที่ไม่สมดุล",
    meaning_rev: "Selfishness, debt, unbalanced giving",
    keywords: ["generosity", "charity", "giving"]
  },
  {
    name_en: "Seven of Pentacles",
    name_th: "เซเว่น ออฟ เพนทาเคิลส์",
    name: "Seven of Pentacles",
    image: "/images/minor_arcana_pentacles_7_result.webp",
    meaning_up_en: "Patience, long-term view, investment",
    meaning_up_th: "ความอดทน, มุมมองระยะยาว, การลงทุน",
    meaning_up: "Patience, long-term view, investment",
    meaning_rev_en: "Impatience, short-sightedness, lack of work",
    meaning_rev_th: "ความใจร้อน, การมองระยะสั้น, ขาดการทำงาน",
    meaning_rev: "Impatience, short-sightedness, lack of work",
    keywords: ["patience", "investment", "growth"]
  },
  {
    name_en: "Eight of Pentacles",
    name_th: "เอท ออฟ เพนทาเคิลส์",
    name: "Eight of Pentacles",
    image: "/images/minor_arcana_pentacles_8_result.webp",
    meaning_up_en: "Craftsmanship, skill, diligence",
    meaning_up_th: "ฝีมือช่าง, ทักษะ, ความขยันหมั่นเพียร",
    meaning_up: "Craftsmanship, skill, diligence",
    meaning_rev_en: "Perfectionism, lack of motivation, poor quality",
    meaning_rev_th: "ความสมบูรณ์แบบ, ขาดแรงจูงใจ, คุณภาพต่ำ",
    meaning_rev: "Perfectionism, lack of motivation, poor quality",
    keywords: ["skill", "diligence", "craftsmanship"]
  },
  {
    name_en: "Nine of Pentacles",
    name_th: "ไนน์ ออฟ เพนทาเคิลส์",
    name: "Nine of Pentacles",
    image: "/images/minor_arcana_pentacles_9_result.webp",
    meaning_up_en: "Luxury, self-sufficiency, financial independence",
    meaning_up_th: "ความหรูหรา, การพึ่งพาตนเอง, ความเป็นอิสระทางการเงิน",
    meaning_up: "Luxury, self-sufficiency, financial independence",
    meaning_rev_en: "Overindulgence, dependency, financial losses",
    meaning_rev_th: "การหลงระเริง, การพึ่งพาผู้อื่น, การสูญเสียทางการเงิน",
    meaning_rev: "Overindulgence, dependency, financial losses",
    keywords: ["luxury", "independence", "self-sufficiency"]
  },
  {
    name_en: "Ten of Pentacles",
    name_th: "เทน ออฟ เพนทาเคิลส์",
    name: "Ten of Pentacles",
    image: "/images/minor_arcana_pentacles_10_result.webp",
    meaning_up_en: "Wealth, inheritance, establishment",
    meaning_up_th: "ความมั่งคั่ง, มรดก, การตั้งมั่น",
    meaning_up: "Wealth, inheritance, establishment",
    meaning_rev_en: "Financial failure, loss of inheritance, family disputes",
    meaning_rev_th: "ความล้มเหลวทางการเงิน, การสูญเสียมรดก, ข้อพิพาทในครอบครัว",
    meaning_rev: "Financial failure, loss of inheritance, family disputes",
    keywords: ["wealth", "family", "inheritance"]
  },
  {
    name_en: "Page of Pentacles",
    name_th: "เพจ ออฟ เพนทาเคิลส์",
    name: "Page of Pentacles",
    image: "/images/minor_arcana_pentacles_page_result.webp",
    meaning_up_en: "Opportunity, study, new project",
    meaning_up_th: "โอกาส, การศึกษา, โครงการใหม่",
    meaning_up: "Opportunity, study, new project",
    meaning_rev_en: "Lack of progress, procrastination, neglect",
    meaning_rev_th: "ขาดความก้าวหน้า, การผัดวันประกันพรุ่ง, การละเลย",
    meaning_rev: "Lack of progress, procrastination, neglect",
    keywords: ["study", "opportunity", "diligence"]
  },
  {
    name_en: "Knight of Pentacles",
    name_th: "ไนท์ ออฟ เพนทาเคิลส์",
    name: "Knight of Pentacles",
    image: "/images/minor_arcana_pentacles_knight_result.webp",
    meaning_up_en: "Hard work, productivity, responsibility",
    meaning_up_th: "การทำงานหนัก, ความสามารถในการผลิต, ความรับผิดชอบ",
    meaning_up: "Hard work, productivity, responsibility",
    meaning_rev_en: "Laziness, boredom, feeling stuck",
    meaning_rev_th: "ความขี้เกียจ, ความเบื่อหน่าย, รู้สึกติดอยู่",
    meaning_rev: "Laziness, boredom, feeling stuck",
    keywords: ["reliable", "routine", "hard work"]
  },
  {
    name_en: "Queen of Pentacles",
    name_th: "ควีน ออฟ เพนทาเคิลส์",
    name: "Queen of Pentacles",
    image: "/images/minor_arcana_pentacles_queen_result.webp",
    meaning_up_en: "Nurturing, practical, financial security",
    meaning_up_th: "การเลี้ยงดู, ปฏิบัติได้, ความมั่นคงทางการเงิน",
    meaning_up: "Nurturing, practical, financial security",
    meaning_rev_en: "Selfish, materialistic, insecure",
    meaning_rev_th: "เห็นแก่ตัว, วัตถุนิยม, ไม่มั่นคง",
    meaning_rev: "Selfish, materialistic, insecure",
    keywords: ["nurturing", "practical", "abundance"]
  },
  {
    name_en: "King of Pentacles",
    name_th: "คิง ออฟ เพนทาเคิลส์",
    name: "King of Pentacles",
    image: "/images/minor_arcana_pentacles_king_result.webp",
    meaning_up_en: "Wealth, business, leadership",
    meaning_up_th: "ความมั่งคั่ง, ธุรกิจ, ความเป็นผู้นำ",
    meaning_up: "Wealth, business, leadership",
    meaning_rev_en: "Corruption, materialism, greed",
    meaning_rev_th: "การทุจริต, วัตถุนิยม, ความโลภ",
    meaning_rev: "Corruption, materialism, greed",
    keywords: ["wealth", "success", "security"]
  }];